In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv('D:\Data Science Projects\glassdoor_jobs.csv')

In [5]:
df

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
0,0,Data Scientist,$53K-$91K (Glassdoor est.),"Data Scientist\nLocation: Albuquerque, NM\nEdu...",3.8,Tecolote Research\n3.8,"Albuquerque, NM","Goleta, CA",501 to 1000 employees,1973,Company - Private,Aerospace & Defense,Aerospace & Defense,$50 to $100 million (USD),-1
1,1,Healthcare Data Scientist,$63K-$112K (Glassdoor est.),What You Will Do:\n\nI. General Summary\n\nThe...,3.4,University of Maryland Medical System\n3.4,"Linthicum, MD","Baltimore, MD",10000+ employees,1984,Other Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1
2,2,Data Scientist,$80K-$90K (Glassdoor est.),"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 to 1000 employees,2010,Company - Private,Security Services,Business Services,$100 to $500 million (USD),-1
3,3,Data Scientist,$56K-$97K (Glassdoor est.),*Organization and Job ID**\nJob ID: 310709\n\n...,3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,Government,Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa..."
4,4,Data Scientist,$86K-$143K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
951,951,Senior Data Engineer,$72K-$133K (Glassdoor est.),THE CHALLENGE\nEventbrite has a world-class da...,4.4,Eventbrite\n4.4,"Nashville, TN","San Francisco, CA",1001 to 5000 employees,2006,Company - Public,Internet,Information Technology,$100 to $500 million (USD),"See Tickets, TicketWeb, Vendini"
952,952,"Project Scientist - Auton Lab, Robotics Institute",$56K-$91K (Glassdoor est.),The Auton Lab at Carnegie Mellon University is...,2.6,Software Engineering Institute\n2.6,"Pittsburgh, PA","Pittsburgh, PA",501 to 1000 employees,1984,College / University,Colleges & Universities,Education,Unknown / Non-Applicable,-1
953,953,Data Science Manager,$95K-$160K (Glassdoor est.),Data Science ManagerResponsibilities:\n\nOvers...,3.2,"Numeric, LLC\n3.2","Allentown, PA","Chadds Ford, PA",1 to 50 employees,-1,Company - Private,Staffing & Outsourcing,Business Services,$5 to $10 million (USD),-1
954,954,Data Engineer,-1,Loading...\n\nTitle: Data Engineer\n\nLocation...,4.8,IGNW\n4.8,"Austin, TX","Portland, OR",201 to 500 employees,2015,Company - Private,IT Services,Information Technology,$25 to $50 million (USD),Slalom
955,955,Research Scientist – Security and Privacy,$61K-$126K (Glassdoor est.),Returning Candidate? Log back in to the Career...,3.6,Riverside Research Institute\n3.6,"Beavercreek, OH","Arlington, VA",501 to 1000 employees,1967,Nonprofit Organization,Federal Agencies,Government,$50 to $100 million (USD),-1

In [6]:
df.dtypes

Unnamed: 0             int64
Job Title             object
Salary Estimate       object
Job Description       object
Rating               float64
Company Name          object
Location              object
Headquarters          object
Size                  object
Founded                int64
Type of ownership     object
Industry              object
Sector                object
Revenue               object
Competitors           object
dtype: object

In [2]:
df = df[df['Salary Estimate']!= '-1']

In [8]:
df

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
0,0,Data Scientist,$53K-$91K (Glassdoor est.),"Data Scientist\nLocation: Albuquerque, NM\nEdu...",3.8,Tecolote Research\n3.8,"Albuquerque, NM","Goleta, CA",501 to 1000 employees,1973,Company - Private,Aerospace & Defense,Aerospace & Defense,$50 to $100 million (USD),-1
1,1,Healthcare Data Scientist,$63K-$112K (Glassdoor est.),What You Will Do:\n\nI. General Summary\n\nThe...,3.4,University of Maryland Medical System\n3.4,"Linthicum, MD","Baltimore, MD",10000+ employees,1984,Other Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1
2,2,Data Scientist,$80K-$90K (Glassdoor est.),"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 to 1000 employees,2010,Company - Private,Security Services,Business Services,$100 to $500 million (USD),-1
3,3,Data Scientist,$56K-$97K (Glassdoor est.),*Organization and Job ID**\nJob ID: 310709\n\n...,3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,Government,Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa..."
4,4,Data Scientist,$86K-$143K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
950,950,"Sr Scientist, Immuno-Oncology - Oncology",$58K-$111K (Glassdoor est.),Site Name: USA - Massachusetts - Cambridge\nPo...,3.9,GSK\n3.9,"Cambridge, MA","Brentford, United Kingdom",10000+ employees,1830,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),"Pfizer, AstraZeneca, Merck"
951,951,Senior Data Engineer,$72K-$133K (Glassdoor est.),THE CHALLENGE\nEventbrite has a world-class da...,4.4,Eventbrite\n4.4,"Nashville, TN","San Francisco, CA",1001 to 5000 employees,2006,Company - Public,Internet,Information Technology,$100 to $500 million (USD),"See Tickets, TicketWeb, Vendini"
952,952,"Project Scientist - Auton Lab, Robotics Institute",$56K-$91K (Glassdoor est.),The Auton Lab at Carnegie Mellon University is...,2.6,Software Engineering Institute\n2.6,"Pittsburgh, PA","Pittsburgh, PA",501 to 1000 employees,1984,College / University,Colleges & Universities,Education,Unknown / Non-Applicable,-1
953,953,Data Science Manager,$95K-$160K (Glassdoor est.),Data Science ManagerResponsibilities:\n\nOvers...,3.2,"Numeric, LLC\n3.2","Allentown, PA","Chadds Ford, PA",1 to 50 employees,-1,Company - Private,Staffing & Outsourcing,Business Services,$5 to $10 million (USD),-1
955,955,Research Scientist – Security and Privacy,$61K-$126K (Glassdoor est.),Returning Candidate? Log back in to the Career...,3.6,Riverside Research Institute\n3.6,"Beavercreek, OH","Arlington, VA",501 to 1000 employees,1967,Nonprofit Organization,Federal Agencies,Government,$50 to $100 million (USD),-1

In [3]:
salary = df['Salary Estimate'].apply(lambda x: x.split('(')[0])

In [5]:
salary

0       $53K-$91K
1      $63K-$112K
2       $80K-$90K
3       $56K-$97K
4      $86K-$143K
          ...
950    $58K-$111K
951    $72K-$133K
952     $56K-$91K
953    $95K-$160K
955    $61K-$126K
Name: Salary Estimate, Length: 742, dtype: object

In [6]:
minus_kd = salary.apply(lambda x:x.replace('K',' ').replace('$',' '))

In [7]:
minus_kd

0        53 - 91
1       63 - 112
2        80 - 90
3        56 - 97
4       86 - 143
          ...
950     58 - 111
951     72 - 133
952      56 - 91
953     95 - 160
955     61 - 126
Name: Salary Estimate, Length: 742, dtype: object

In [8]:
df['hourly']= df['Salary Estimate'].apply(lambda x: 1 if 'per hour'in x.lower() else 0)

In [11]:
df['employer provided salary'] = df['Salary Estimate'].apply(lambda x: 1 if 'employer provided salary'in x.lower()else 0)

In [14]:
pd.set_option('display.max_rows',1000)

In [15]:
df['employer provided salary']

0      0
1      0
2      0
3      0
4      0
5      0
6      0
7      0
8      0
9      0
10     0
11     0
12     0
13     0
14     0
15     0
16     0
17     0
18     0
19     0
20     0
21     0
22     0
23     0
25     0
26     0
27     0
28     0
29     0
30     0
31     0
32     0
33     0
34     0
35     0
36     0
37     0
38     0
39     0
40     0
41     0
43     0
44     0
45     0
46     0
48     1
49     0
50     0
51     0
52     0
54     0
55     0
56     0
57     0
58     0
59     0
60     0
61     0
62     0
63     0
65     0
66     0
67     0
68     0
70     0
72     0
73     0
75     0
76     0
77     0
78     0
79     0
80     0
81     0
82     0
83     0
84     0
85     0
86     0
87     0
88     0
89     0
90     0
91     0
92     0
93     0
94     0
95     0
96     0
97     0
99     0
101    0
102    0
104    0
105    0
106    0
107    0
108    0
109    0
110    0
112    0
113    0
116    0
117    0
118    0
119    0
120    0
122    0
123    0
124    0
125    0
126    0
127    0
128    0
129    0
130    0
131    0
132    0
136    0
137    0
138    0
139    0
140    0
141    0
142    0
143    0
145    0
146    0
147    0
148    0
150    0
152    0
153    0
154    0
156    0
157    0
158    0
159    0
161    1
162    0
164    0
166    0
167    0
168    0
169    0
170    0
171    0
172    0
174    0
175    0
177    0
178    0
179    0
180    0
181    0
182    0
183    0
185    0
187    0
188    0
190    0
191    0
192    0
193    0
194    0
197    0
198    0
199    0
200    0
201    0
202    0
203    0
204    0
205    0
206    0
207    0
208    1
209    0
210    0
211    0
212    0
213    0
215    0
216    0
217    0
221    0
223    0
224    0
225    0
226    0
228    0
229    0
230    0
233    0
234    0
235    0
239    0
240    0
242    0
243    0
245    0
246    0
247    0
248    0
250    0
251    0
253    0
254    0
255    0
256    0
257    0
258    0
259    0
260    0
262    0
263    0
264    0
265    0
266    0
267    0
268    0
269    0
270    0
273    0
274    0
275    0
276    0
277    0
278    0
281    0
282    0
284    0
285    0
288    0
289    0
290    0
291    0
292    0
293    0
295    0
296    0
299    0
300    0
302    0
305    0
306    0
307    0
308    0
309    0
310    0
311    0
312    0
313    0
314    0
316    0
317    0
318    0
319    0
320    0
322    0
323    0
324    0
325    0
326    0
328    0
330    0
331    1
332    0
333    0
334    0
335    0
337    0
339    0
341    0
342    0
344    0
346    0
347    0
348    0
349    0
350    0
351    0
352    0
353    0
354    0
355    0
356    0
357    0
358    0
362    0
364    0
366    0
367    0
368    0
369    0
370    0
371    0
372    0
375    0
376    0
377    1
379    0
380    0
381    0
382    0
383    0
384    0
386    0
387    0
388    0
390    0
391    0
392    0
394    0
396    0
397    0
398    0
399    0
400    0
401    0
403    0
406    0
407    0
409    0
410    0
411    0
412    0
413    0
414    0
415    0
416    0
417    0
419    0
420    0
421    0
425    0
426    0
427    0
428    0
429    0
430    0
431    0
433    0
434    0
435    0
437    0
442    0
443    0
444    0
446    0
447    0
448    0
449    0
450    0
452    0
454    0
455    0
456    0
458    0
459    0
461    0
462    0
463    0
464    1
466    0
467    0
468    0
469    0
470    0
471    0
472    1
473    0
476    0
477    1
479    0
482    0
483    0
485    0
486    0
487    0
488    0
489    0
490    0
491    0
492    0
493    0
494    0
495    0
496    0
497    0
498    0
499    0
500    0
501    0
502    0
505    0
506    0
507    0
508    0
509    0
510    0
512    0
516    0
517    0
518    1
519    0
520    0
521    0
522    0
523    0
524    0
525    0
526    0
528    0
530    0
532    0
533    0
534    0
535    0
537    0
538    0
539    0
540    0
541    0
542    0
543    0
544    0
545    0
546    0
548    0
549    0
550    0
552    0
554    0
555    0
556    0
557    0
558    0
560    0
561    0
562    0
563    0
565    0
566    0
567    0
568    0
570    0
572    0
573    0
575    0
576    0
577    0
578    0
579    0
580    0
582    0
583    0
585    0
586    0
587    0
588    0
589    0
590    0
591    0
594    0
595    0
597    0
599    0
600    0
601    0
602    0
603    0
604    0
605    0
606    0
607    0
608    0
609    0
610    0
613    0
614    0
616    0
617    0
619    0
622    0
623    0
624    0
625    0
627    0
629    0
630    0
631    0
632    0
633    0
634    0
635    0
636    0
637    0
638    0
639    0
640    0
642    0
643    0
644    0
645    0
646    0
647    0
648    0
651    0
652    0
653    0
654    0
655    0
658    0
660    0
661    0
662    0
663    0
664    0
665    0
666    0
668    0
669    0
670    0
671    0
672    0
673    0
674    0
675    0
676    0
678    0
679    0
681    0
682    0
683    0
685    0
687    0
688    0
689    0
690    0
691    0
692    0
694    1
695    0
696    0
697    0
698    0
699    0
700    0
701    0
702    0
703    1
704    0
705    0
706    0
707    0
708    0
709    0
711    0
712    0
714    0
715    0
718    0
719    0
721    0
722    0
723    0
725    0
726    0
727    0
728    0
730    0
731    0
732    0
733    0
734    0
735    0
736    0
737    0
738    0
740    0
741    1
742    0
743    0
744    0
745    0
746    0
747    0
748    0
749    0
750    0
751    0
752    0
753    0
754    0
755    0
756    0
757    0
758    0
759    0
761    0
763    0
766    0
767    0
768    0
769    0
773    0
776    0
777    0
778    1
779    0
780    0
781    0
782    0
783    0
784    0
785    0
786    0
787    0
788    0
789    0
790    0
791    0
794    0
795    0
797    0
799    0
802    0
803    0
804    0
806    0
807    0
808    0
809    0
810    0
811    0
812    0
815    0
816    0
817    0
818    0
819    1
820    0
821    0
822    0
823    0
824    0
825    0
826    0
827    0
828    0
829    0
830    0
831    0
832    0
836    0
837    0
838    0
839    0
840    0
841    0
845    0
848    0
851    0
852    0
853    0
854    0
855    0
856    0
857    0
858    0
859    0
860    0
861    0
863    0
864    0
866    0
867    0
868    0
869    0
870    0
871    0
875    0
877    0
878    0
879    0
880    0
881    0
883    0
884    0
886    0
887    0
892    0
893    1
895    0
896    0
897    0
898    0
899    0
900    0
901    0
902    0
904    0
907    0
909    0
910    0
911    0
912    0
913    0
914    0
916    0
919    0
920    0
921    0
924    0
926    0
928    0
929    0
930    0
931    0
932    0
933    0
934    0
935    0
936    1
938    0
939    0
940    0
941    0
942    0
943    1
944    0
945    0
946    0
947    0
948    0
949    0
950    0
951    0
952    0
953    0
955    0
Name: employer provided salary, dtype: int64

In [19]:
df['hourly']

0      0
1      0
2      0
3      0
4      0
5      0
6      0
7      0
8      0
9      0
10     0
11     0
12     0
13     0
14     0
15     0
16     0
17     0
18     0
19     0
20     0
21     0
22     0
23     0
25     0
26     0
27     0
28     0
29     0
30     0
31     0
32     0
33     0
34     0
35     0
36     0
37     0
38     0
39     0
40     0
41     0
43     0
44     0
45     0
46     0
48     0
49     0
50     0
51     0
52     0
54     0
55     0
56     0
57     0
58     0
59     0
60     0
61     0
62     0
63     0
65     0
66     0
67     0
68     0
70     0
72     0
73     0
75     0
76     0
77     0
78     0
79     0
80     0
81     0
82     0
83     0
84     0
85     0
86     0
87     0
88     0
89     0
90     0
91     0
92     0
93     0
94     0
95     0
96     0
97     0
99     0
101    0
102    0
104    0
105    0
106    0
107    0
108    0
109    0
110    0
112    0
113    0
116    0
117    0
118    0
119    0
120    0
122    0
123    0
124    0
125    0
126    0
127    0
128    0
129    0
130    0
131    0
132    0
136    0
137    0
138    0
139    0
140    0
141    0
142    0
143    0
145    0
146    0
147    0
148    0
150    0
152    0
153    0
154    0
156    0
157    0
158    0
159    0
161    0
162    0
164    0
166    0
167    0
168    0
169    0
170    0
171    0
172    0
174    0
175    0
177    0
178    0
179    0
180    0
181    0
182    0
183    0
185    0
187    0
188    0
190    0
191    0
192    0
193    0
194    0
197    1
198    0
199    0
200    0
201    0
202    0
203    0
204    0
205    0
206    0
207    0
208    0
209    1
210    0
211    0
212    0
213    0
215    0
216    0
217    0
221    0
223    0
224    0
225    0
226    0
228    0
229    0
230    0
233    0
234    0
235    0
239    0
240    1
242    0
243    0
245    0
246    0
247    1
248    0
250    0
251    0
253    0
254    0
255    0
256    0
257    1
258    0
259    0
260    0
262    0
263    0
264    0
265    0
266    0
267    0
268    0
269    0
270    0
273    0
274    0
275    0
276    0
277    0
278    0
281    0
282    0
284    0
285    0
288    0
289    0
290    0
291    0
292    0
293    0
295    0
296    0
299    0
300    0
302    0
305    0
306    0
307    1
308    0
309    0
310    0
311    0
312    0
313    0
314    0
316    0
317    0
318    0
319    0
320    0
322    0
323    0
324    0
325    0
326    0
328    0
330    0
331    0
332    0
333    0
334    0
335    0
337    1
339    0
341    0
342    0
344    0
346    0
347    0
348    0
349    0
350    0
351    0
352    0
353    0
354    0
355    0
356    0
357    0
358    0
362    0
364    0
366    0
367    0
368    0
369    0
370    0
371    0
372    0
375    0
376    0
377    0
379    0
380    0
381    0
382    0
383    0
384    0
386    0
387    0
388    0
390    0
391    0
392    0
394    0
396    0
397    0
398    0
399    0
400    0
401    0
403    0
406    0
407    0
409    0
410    0
411    0
412    0
413    0
414    0
415    0
416    0
417    0
419    0
420    0
421    0
425    0
426    0
427    1
428    0
429    0
430    0
431    0
433    0
434    0
435    0
437    1
442    0
443    0
444    0
446    0
447    0
448    0
449    0
450    0
452    0
454    0
455    0
456    1
458    0
459    0
461    0
462    0
463    0
464    1
466    0
467    0
468    0
469    0
470    0
471    0
472    0
473    0
476    0
477    0
479    0
482    0
483    0
485    0
486    0
487    0
488    0
489    0
490    0
491    0
492    0
493    0
494    0
495    0
496    0
497    0
498    0
499    0
500    0
501    0
502    0
505    0
506    0
507    0
508    0
509    0
510    0
512    0
516    0
517    0
518    0
519    0
520    0
521    0
522    1
523    1
524    0
525    0
526    0
528    0
530    0
532    0
533    0
534    0
535    0
537    0
538    0
539    0
540    0
541    0
542    0
543    0
544    0
545    0
546    0
548    0
549    0
550    0
552    0
554    0
555    0
556    0
557    0
558    0
560    0
561    0
562    0
563    0
565    0
566    0
567    0
568    0
570    0
572    0
573    0
575    0
576    0
577    0
578    0
579    0
580    0
582    0
583    0
585    0
586    0
587    0
588    0
589    0
590    0
591    0
594    0
595    0
597    0
599    0
600    0
601    0
602    0
603    0
604    0
605    0
606    0
607    0
608    0
609    0
610    0
613    0
614    0
616    0
617    0
619    0
622    0
623    0
624    0
625    0
627    0
629    0
630    0
631    0
632    1
633    0
634    0
635    0
636    0
637    0
638    0
639    0
640    0
642    0
643    0
644    0
645    0
646    0
647    0
648    0
651    0
652    1
653    0
654    0
655    0
658    0
660    0
661    0
662    0
663    0
664    0
665    0
666    0
668    0
669    0
670    0
671    0
672    0
673    0
674    0
675    0
676    0
678    0
679    0
681    0
682    1
683    0
685    0
687    0
688    0
689    0
690    0
691    0
692    0
694    1
695    0
696    0
697    0
698    0
699    0
700    0
701    0
702    0
703    0
704    0
705    0
706    0
707    0
708    0
709    0
711    0
712    0
714    0
715    0
718    0
719    0
721    0
722    0
723    0
725    0
726    0
727    0
728    0
730    0
731    0
732    0
733    0
734    0
735    0
736    0
737    0
738    0
740    0
741    0
742    0
743    0
744    0
745    0
746    0
747    0
748    0
749    0
750    0
751    0
752    0
753    0
754    0
755    0
756    0
757    0
758    0
759    0
761    0
763    0
766    0
767    0
768    0
769    0
773    0
776    0
777    0
778    0
779    0
780    0
781    0
782    0
783    0
784    0
785    0
786    1
787    1
788    0
789    0
790    0
791    0
794    0
795    0
797    0
799    0
802    0
803    0
804    0
806    0
807    0
808    0
809    0
810    0
811    0
812    0
815    0
816    0
817    0
818    0
819    0
820    0
821    0
822    0
823    1
824    0
825    0
826    0
827    0
828    0
829    0
830    0
831    0
832    0
836    0
837    0
838    0
839    0
840    0
841    0
845    0
848    0
851    0
852    0
853    0
854    1
855    0
856    0
857    0
858    0
859    0
860    0
861    0
863    0
864    0
866    0
867    0
868    0
869    0
870    0
871    0
875    1
877    0
878    0
879    0
880    0
881    0
883    0
884    0
886    0
887    0
892    0
893    0
895    0
896    0
897    0
898    0
899    0
900    0
901    0
902    0
904    0
907    0
909    0
910    0
911    0
912    0
913    0
914    0
916    0
919    1
920    0
921    0
924    0
926    0
928    0
929    0
930    0
931    0
932    0
933    0
934    0
935    0
936    1
938    0
939    0
940    0
941    0
942    0
943    0
944    0
945    0
946    0
947    0
948    0
949    0
950    0
951    0
952    0
953    0
955    0
Name: hourly, dtype: int64

In [35]:
minus_hr = minus_kd.apply(lambda x: x.lower().replace('per hour','').replace('employer provided salary','').replace(':',''))

In [37]:
df['min_salary']= minus_hr.apply(lambda x: int(x.split('-')[0]))

In [27]:
df['min_salary']

0         53
1         63
2         80
3         56
4         86
5         71
6         54
7         86
8         38
9        120
10       126
11        64
12       106
13        46
14        83
15       102
16        67
17       118
18       110
19        64
20        81
21        73
22        86
23        63
25       109
26        63
27        75
28        34
29        63
30        80
31        56
32        72
33        86
34        93
35        85
36        77
37        82
38        83
39       115
40        74
41        64
43        68
44       110
45        52
46       110
48     : 150
49       158
50        20
51        56
52        63
54        68
55        86
56        41
57        86
58        80
59        56
60       120
61       111
62        54
63        71
65        82
66        84
67       107
68        49
70        61
72        88
73        60
75        41
76        96
77        65
78        52
79       139
80        50
81        85
82        74
83        99
84        79
85        57
86        83
87        86
88        94
89        37
90       100
91        55
92        60
93        39
94       106
95        86
96        64
97        31
99        34
101      117
102       64
104       79
105       52
106       55
107       72
108       74
109       40
110      102
112       89
113       61
116       65
117      200
118       68
119       80
120       41
122       39
123       38
124      121
125       54
126       83
127      120
128      102
129       76
130       60
131       82
132       65
136       91
137       95
138       77
139       80
140       85
141       80
142       43
143       29
145       82
146       26
147       61
148       60
150      112
152       64
153       51
154      113
156       72
157       71
158       64
159      118
161    : 120
162       80
164       80
166       59
167       71
168       81
169       49
170       60
171       71
172       75
174       77
175       74
177       44
178       65
179       59
180       85
181      124
182      131
183      110
185       52
187       81
188      132
190       73
191      110
192       74
193      100
194       43
197        17
198       91
199       42
200      116
201       59
202       48
203       31
204      105
205       55
206       98
207       73
208    : 200
209        21
210      117
211      111
212       44
213       81
215       83
216      114
217       42
221      114
223       60
224      100
225      108
226       48
228       54
229       60
230       90
233      138
234       54
235      190
239       35
240        18
242       39
243       81
245       42
246       69
247        21
248       40
250       49
251       75
253       86
254       66
255       76
256       44
257        15
258       53
259       44
260       85
262       59
263       64
264       65
265       60
266       53
267      124
268      131
269      110
270       33
273       52
274       48
275       34
276      132
277       81
278       42
281       66
282       74
284       63
285       63
288       91
289      100
290       62
291       71
292       43
293       74
295       55
296       15
299       61
300       91
302      127
305       74
306       33
307        17
308       37
309       67
310       72
311      116
312       78
313       42
314       59
316       63
317      109
318      116
319       48
320       83
322      105
323       31
324       98
325       55
326       45
328       83
330       70
331    : 200
332       70
333       73
334       54
335      117
337        21
339      111
341       68
342       42
344       44
346       81
347       95
348       75
349       72
350       76
351      114
352      108
353      130
354       83
355       42
356       37
357       52
358      105
362       71
364       39
366      114
367       88
368       60
369      100
370       55
371       67
372       92
375      116
376       38
377     : 85
379       62
380       86
381       93
382       84
383       60
384       52
386       48
387       56
388       65
390      108
391       63
392       54
394       90
396      127
397       31
398       60
399       75
400      105
401       45
403       95
406       80
407       36
409       54
410       50
411       67
412       82
413       85
414      138
415       42
416      190
417       68
419       34
420       54
421       65
425       35
426      109
427        18
428       61
429       39
430       43
431       74
433      113
434       81
435       97
437        24
442       42
443       69
444      110
446      102
447       74
448       40
449      108
450       76
452      202
454       49
455       49
456        21
458       65
459       32
461       87
462      107
463       56
464      : 25
466       80
467       43
468       45
469       44
470       50
471       61
472    : 100
473       56
476       68
477    : 150
479      101
482      125
483       43
485      139
486       44
487       78
488       65
489       37
490       38
491       43
492       90
493       61
494       93
495       52
496       40
497       97
498       81
499       84
500       49
501       68
502       75
505      121
506       52
507       81
508       63
509      110
510       83
512       60
516       31
517      102
518    : 110
519       48
520       66
521       92
522        21
523        10
524      150
525       52
526       82
528       47
530       49
532       43
533      124
534       52
535       97
537      100
538       53
539       65
540       56
541      111
542       75
543       65
544       56
545      108
546       94
548      176
549       92
550       63
552       54
554      118
555      108
556       65
557       55
558       94
560       63
561       90
562      127
563       60
565       31
566      105
567       45
568       75
570      126
572       80
573      120
575       85
576       95
577      111
578       87
579       76
580       54
582       61
583       81
585       80
586      108
587      112
588       63
589       75
590      110
591       76
594       36
595       70
597       94
599       54
600       50
601       49
602       67
603      138
604       80
605      158
606      150
607       42
608      190
609       42
610       68
613       54
614       34
616       47
617       65
619       56
622       62
623      107
624       64
625       89
627      109
629       61
630       35
631       55
632        18
633       39
634      135
635       57
636      129
637       86
638       63
639       50
640       43
642       74
643       71
644      113
645       81
646       69
647       97
648      150
651       77
652        24
653       59
654       35
655       79
658       62
660      119
661       90
662       32
663       42
664      116
665      102
666       69
668       86
669      102
670       74
671       40
672       76
673       76
674      108
675      202
676       91
678       80
679       49
681       49
682        21
683       65
685       32
687       39
688       87
689       27
690       36
691      107
692       56
694      : 25
695       80
696       43
697       44
698       45
699       50
700       60
701      130
702       61
703    : 100
704       99
705       86
706       37
707       58
708       72
709       56
711       61
712       95
714       53
715      101
718       33
719       44
721       43
722      125
723       44
725       69
726       65
727       67
728       78
730       66
731       37
732       86
733       84
734       50
735       38
736       90
737       92
738       90
740       43
741    : 100
742       93
743       61
744       42
745      139
746       40
747       84
748       52
749       81
750       97
751       49
752       44
753       75
754       84
755       40
756       68
757       72
758       74
759       57
761      121
763       52
766       81
767       83
768       59
769       60
773       31
776      102
777      136
778    : 110
779       48
780       71
781       66
782      171
783       92
784       65
785      150
786        21
787        10
788      118
789       82
790       52
791       47
794       49
795       43
797       61
799      113
802      124
803       58
804       52
806       97
807      100
808       58
809       81
810       53
811       61
812       65
815      115
816       71
817       32
818       79
819    : 120
820       50
821       68
822       48
823        27
824       74
825       68
826       39
827       71
828      107
829       49
830       54
831       61
832       47
836       65
837       87
838       56
839       71
840       62
841       64
845       89
848      109
851       35
852       61
853       55
854        18
855      135
856       39
857       57
858       63
859       50
860       82
861       85
863       72
864       74
866      113
867       69
868       71
869       97
870       81
871      150
875        24
877       35
878       77
879       51
880      101
881       59
883       79
884       79
886       62
887      119
892       81
893    : 120
895       90
896       63
897       42
898       32
899      116
900      107
901       65
902       69
904      102
907       74
909       40
910       76
911       76
912      108
913      202
914       91
916       80
919        21
920       49
921       49
924       96
926       65
928       59
929       32
930       87
931       27
932       39
933       36
934      107
935       56
936      : 25
938       80
939       43
940       45
941       50
942       44
943    : 100
944       61
945       80
946       99
947       37
948       62
949       86
950       58
951       72
952       56
953       95
955       61
Name: min_salary, dtype: object

In [32]:
df['max_salary']= minus_hr.apply(lambda x: int(x.split('-')[1]))

In [38]:
df['avg_salary'] = (df.min_salary + df.max_salary)/2

In [46]:
df['Company Name'] = df.apply(lambda x: x['Company Name'] if x['Rating']<0 else x['Company Name'][:-3], axis =1)

In [49]:
df['Job State']= df['Location'].apply(lambda x: x.split(',')[1])

In [54]:
df['Job State'].value_counts()

 CA             151
 MA             103
 NY              72
 VA              41
 IL              40
 MD              35
 PA              33
 TX              28
 WA              21
 NC              21
 NJ              17
 FL              16
 OH              14
 TN              13
 DC              11
 CO              11
 WI              10
 IN              10
 UT              10
 AZ               9
 MO               9
 AL               8
 GA               6
 KY               6
 DE               6
 MI               6
 CT               5
 IA               5
 LA               4
 OR               4
 NE               4
 NM               3
 KS               3
 ID               2
 MN               2
 Los Angeles      1
 RI               1
 SC               1
Name: Job State, dtype: int64

In [61]:
df['same_state'] = df.apply(lambda x:1 if x.Location==x.Headquarters else 0, axis = 1)

In [63]:
df['Company_age']= df['Founded'].apply(lambda x: x if x<1 else 2022-x)

In [65]:
df['python_dep'] = df['Job Description'].apply(lambda x:1 if 'python'in x.lower() else 0)

In [66]:
df.python_dep.value_counts()

1    392
0    350
Name: python_dep, dtype: int64

In [68]:
df['R']= df['Job Description'].apply(lambda x: 1 if 'r studio'in x.lower() else 0)

In [69]:
df.R.value_counts()

0    741
1      1
Name: R, dtype: int64

In [70]:
df['spark']= df['Job Description'].apply(lambda x: 1 if 'spark'in x.lower() else 0)

In [71]:
df['Excel']= df['Job Description'].apply(lambda x: 1 if 'excel'in x.lower() else 0)

In [78]:
df_out = df.drop(['Unnamed: 0'], axis=1) #dropping the unnamed column

In [80]:
df_out.to_csv('Salary_data_cleaned', index=False)

In [85]:
pd.read_csv('Salary_data_cleaned')

                                             Job Title  \
0                                       Data Scientist
1                            Healthcare Data Scientist
2                                       Data Scientist
3                                       Data Scientist
4                                       Data Scientist
5                                       Data Scientist
6                                       Data Scientist
7                                       Data Scientist
8                                   Research Scientist
9                                       Data Scientist
10                                      Data Scientist
11                                      Data Scientist
12                   Staff Data Scientist - Technology
13                                        Data Analyst
14                                      Data Scientist
15                                     Data Engineer I
16                             Scientist I/II, Biology
17                             Customer Data Scientist
18              Data Scientist - Health Data Analytics
19                                      Data Scientist
20                                      Data Scientist
21            Senior Data Scientist / Machine Learning
22                       Data Scientist - Quantitative
23                                      Data Scientist
24                                      Data Scientist
25                       Digital Health Data Scientist
26                                      Data Scientist
27                              Associate Data Analyst
28                             Clinical Data Scientist
29                                      Data Scientist
30                                      Data Scientist
31                                      Data Scientist
32            Data Scientist / Machine Learning Expert
33                                      Data Scientist
34                                      Data Scientist
35                                    Web Data Analyst
36                                      Data Scientist
37                                      Data Scientist
38                               Senior Data Scientist
39                                       Data Engineer
40                                        Data Analyst
41                                       Data Engineer
42             Data Scientist - Algorithms & Inference
43                                           Scientist
44                               Senior Data Scientist
45                                      Data Scientist
46                                 Lead Data Scientist
47                              Associate Data Analyst
48                         Spectral Scientist/Engineer
49   College Hire - Data Scientist - Open to Decemb...
50                                      Data Scientist
51              Data Scientist, Office of Data Science
52                                Data Science Analyst
53                                      Data Scientist
54                                      Data Scientist
55                                      Data Scientist
56                                      Data Scientist
57                                      Data Scientist
58                                      Data Scientist
59                                      Data Scientist
60                               Senior Data Scientist
61                                      Data Scientist
62                          Senior Risk Data Scientist
63   Data Scientist in Artificial Intelligence Earl...
64                                      Data Scientist
65                                      Data Scientist
66                                      Data Scientist
67                           Data Scientist - Research
68                                      Data Scientist
69                         R&D Data Analysis Scientist
70                                Analytics Consultant
71                              Director, Data Science
72                                           Scientist
73                                   Data Scientist SR
74                                      Data Scientist
75                               R&D Sr Data Scientist
76         Customer Data Scientist/Sales Engineer (Bay
77                                  Research Scientist
78                                      Data Scientist
79                                      Data Scientist
80                                      Data Scientist
81                           Jr. Business Data Analyst
82                                      Data Scientist
83                                        Data Analyst
84                                       Data Engineer
85                                        Data Analyst
86                   Staff Data Scientist - Technology
87                                      Data Scientist
88                                      Data Scientist
89                          Data Management Specialist
90                             E-Commerce Data Analyst
91                                    Sr. Scientist II
92                            Insurance Data Scientist
93                                        Data Modeler
94                            Data Analyst / Scientist
95                                           Scientist
96                                      Data Scientist
97                                      Data Scientist
98                                        Data Analyst
99                                 Lead Data Scientist
100                                     Data Scientist
101                                     Data Scientist
102                    Data Scientist, Rice University
103                              Senior Data Scientist
104                                      Data Engineer
105                              Senior Data Scientist
106                             Financial Data Analyst
107                                Senior Data Analyst
108                                 Research Scientist
109                                     Data Scientist
110                                      Data Engineer
111                                     Data Scientist
112                                     Data Scientist
113                                     Data Scientist
114                                      Data Engineer
115                                  Ag Data Scientist
116                                     Data Scientist
117                                      Data Engineer
118                                  Data Scientist II
119                               Senior Data Engineer
120                                     Data Scientist
121                                     Data Scientist
122                                      Data Engineer
123                                      Data Engineer
124                                       Data Analyst
125                                  Project Scientist
126                                     Data Scientist
127                             Data Analytics Manager
128  Senior Machine Learning (ML) Engineer / Data S...
129                                     Data Scientist
130                              Senior Data Scientist
131                                     Data Scientist
132                                Associate Scientist
133                       Scientist 2, QC Viral Vector
134                          Machine Learning Engineer
135                         Data Scientist/ML Engineer
136                                     Data Scientist
137                            Customer Data Scientist
138                                      Data Engineer
139                                      Data Engineer
140                                 Sr. Data Scientist
141                         Data Engineer 4 - Contract
142                    Data Analyst - Asset Management
143  Senior Research Scientist - Embedded System De...
144                    Data Scientist - Bioinformatics
145                                      Data Engineer
146             Customer Data Scientist/Sales Engineer
147                                Lead Data Scientist
148                           MongoDB Data Engineer II
149                   Senior Data Scientist Statistics
150                                Senior Data Analyst
151               Senior Spark Engineer (Data Science)
152                                      Data Engineer
153                    BI & Platform Analytics Manager
154                                Lead Data Scientist
155  Sr. Data Scientist - Analytics, Personalized H...
156                              Senior Data Scientist
157  Pricipal Scientist Molecular and cellular biol...
158               Data Scientist (Actuary, FSA or ASA)
159                               Staff Data Scientist
160           Senior Data Scientist / Machine Learning
161             Data Scientist - Health Data Analytics
162                Data Engineer 5 - Contract (Remote)
163                    Senior Scientist - Neuroscience
164                                Senior Data Analyst
165                              Medical Lab Scientist
166              Risk and Analytics IT, Data Scientist
167                  Scientist, Analytical Development
168                              Senior Data Scientist
169                                  Analytics Manager
170                                      Data Engineer
171         Digital Marketing & ECommerce Data Analyst
172  Sr. Scientist - Digital & Image Analysis/Compu...
173                                Senior Data Analyst
174                 Principal Scientist - Immunologist
175                              Senior Data Scientist
176  Principal Data Scientist with over 10 years ex...
177                MED TECH/LAB SCIENTIST - LABORATORY
178  Sr. Scientist, Quantitative Translational Scie...
179                              Sr. Data Scientist II
180                     Excel / VBA / SQL Data Analyst
181                Machine Learning Research Scientist
182                                   VP, Data Science
183                              Senior Data Scientist
184                                 Radar Data Analyst
185                   PL Actuarial-Lead Data Scientist
186                                       PV Scientist
187           Senior Data & Machine Learning Scientist
188  Principal Data Scientist (Computational Chemis...
189                                      Data Engineer
190        Principal Scientist, Chemistry & Immunology
191             Software Engineer - Data Visualization
192             Scientist/Senior Scientist, Autoimmune
193                    Staff Machine Learning Engineer
194                    Principal Scientist, Hematology
195                                 Lead Data Engineer
196                             Marketing Data Analyst
197                       Medical Laboratory Scientist
198                     R&D Specialist/ Food Scientist
199         Senior Research Scientist-Machine Learning
200                      Analytics Manager - Data Mart
201        Sr. Data Engineer - Contract-to-Hire (Java)
202          MED TECH/LAB SCIENTIST- SOUTH COASTAL LAB
203                         Food Scientist - Developer
204     Staff Scientist-Downstream Process Development
205                                  Sr. Data Engineer
206                      Data Scientist - Quantitative
207                                     Data Scientist
208       Senior Research Statistician- Data Scientist
209                         Business Data Analyst, SQL
210  Medical Technologist / Clinical Laboratory Sci...
211                                     Data Scientist
212                                Senior Data Analyst
213                    BI & Platform Analytics Manager
214                                      Data Engineer
215                                     Data Scientist
216                                       Data Analyst
217        Associate Data Scientist/Computer Scientist
218          Business Intelligence Analyst / Developer
219                                Lead Data Scientist
220  Sr. Data Scientist - Analytics, Personalized H...
221                              Senior Data Scientist
222                                       Data Analyst
223  Pricipal Scientist Molecular and cellular biol...
224                                       Data Analyst
225                                       Data Analyst
226                               Staff Data Scientist
227               Data Scientist (Actuary, FSA or ASA)
228                            System and Data Analyst
229                                     Data Scientist
230                Data Engineer 5 - Contract (Remote)
231                      Digital Health Data Scientist
232                                     Data Scientist
233                  Data & Analytics Consultant (NYC)
234                    Senior Scientist - Neuroscience
235                                      Data Engineer
236   Big Data Engineer - Chicago - Future Opportunity
237                                Senior Data Analyst
238                                     Data Scientist
239                                Survey Data Analyst
240                                     Data Scientist
241                                     Data Scientist
242              Risk and Analytics IT, Data Scientist
243                                     Data Scientist
244               Lead Health Data Analyst - Front End
245                                 Research Scientist
246                              Medical Lab Scientist
247                                Junior Data Analyst
248                                  SQL Data Engineer
249                                     Data Scientist
250                              Senior Data Scientist
251                                     Data Scientist
252                  Scientist, Analytical Development
253                                  Analytics Manager
254                            Clinical Data Scientist
255                                     Data Scientist
256     Sr. Data Scientist, Cyber-Security LT Contract
257                                      Data Engineer
258                                     Data Scientist
259  Sr. Scientist - Digital & Image Analysis/Compu...
260         Digital Marketing & ECommerce Data Analyst
261                 Principal Scientist - Immunologist
262                                Senior Data Analyst
263                   Insurance Financial Data Analyst
264                                     Data Scientist
265                                     Data Scientist
266  Principal Data Scientist with over 10 years ex...
267                                      Data Engineer
268                              Senior Data Scientist
269                            Data Engineer I - Azure
270  Sr. Scientist, Quantitative Translational Scie...
271                MED TECH/LAB SCIENTIST - LABORATORY
272                              Sr. Data Scientist II
273                                     Data Scientist
274                  Information Security Data Analyst
275                     Excel / VBA / SQL Data Analyst
276                Machine Learning Research Scientist
277                                     Data Scientist
278                                     Data Scientist
279                                     Data Scientist
280                                     Data Scientist
281                              Senior Data Scientist
282                             Data Scientist, Senior
283                              Senior Data Scientist
284                                   VP, Data Science
285                                 Radar Data Analyst
286                   CONSULTANT– DATA ANALYTICS GROUP
287                                      Data Engineer
288                              Senior Data Scientist
289  Data Engineer, Data Engineering and Artifical ...
290                                    Staff Scientist
291                   PL Actuarial-Lead Data Scientist
292  Associate Scientist/Scientist, Process Analyti...
293                                   Sr. Data Analyst
294           Senior Data & Machine Learning Scientist
295                               Program/Data Analyst
296                                      Data Engineer
297  Senior Data Scientist: Causal & Predictive ana...
298  Principal Data Engineer, Data Platform & Insights
299             RESEARCH SCIENTIST - BIOLOGICAL SAFETY
300                               Data Operations Lead
301                                  Big Data Engineer
302           Data Scientist / Machine Learning Expert
303                                     Data Scientist
304                              Senior Data Scientist
305                                       PV Scientist
306                              Clinical Data Analyst
307                                      Data Engineer
308               Computational Chemist/Data Scientist
309                                      Data Engineer
310  Principal Data Scientist (Computational Chemis...
311                    Product Engineer – Data Science
312        Principal Scientist, Chemistry & Immunology
313             Scientist/Senior Scientist, Autoimmune
314                                     Data Scientist
315                                Market Data Analyst
316             Software Engineer - Data Visualization
317                                      Data Engineer
318                                Staff Data Engineer
319                            Associate Data Engineer
320                              Senior Data Scientist
321                         Staff BI and Data Engineer
322                             Marketing Data Analyst
323                    Principal Scientist, Hematology
324                                       Data Analyst
325         Director - Data, Privacy and AI Governance
326                                     Data Scientist
327                                     Data Scientist
328                    Staff Machine Learning Engineer
329                  Information Security Data Analyst
330                                 Lead Data Engineer
331   Scientist Manufacturing - Kentucky BioProcessing
332                     Data Analytics Project Manager
333                  Consultant - Analytics Consulting
334                                      Data Engineer
335                             Marketing Data Analyst
336                    Senior Scientist (Neuroscience)
337                       Medical Laboratory Scientist
338             Machine Learning Engineer - Regulatory
339                     R&D Specialist/ Food Scientist
340                                      Data Engineer
341                            Scientist, Bacteriology
342  Associate Director, Platform and DevOps- Data ...
343         Senior Research Scientist-Machine Learning
344                              Senior Data Scientist
345                      Clinical Laboratory Scientist
346                      Analytics Manager - Data Mart
347        Sr. Data Engineer - Contract-to-Hire (Java)
348            Data Scientist - Algorithms & Inference
349               Senior Data Scientist - R&D Oncology
350                                      Data Engineer
351                         Food Scientist - Developer
352                              Senior Data Scientist
353                                      Data Engineer
354          Director II, Data Science - GRM Actuarial
355            Scientist, Molecular/Cellular Biologist
356     Staff Scientist-Downstream Process Development
357          MED TECH/LAB SCIENTIST- SOUTH COASTAL LAB
358                    Scientist - Analytical Services
359  Associate Data Analyst- Graduate Development P...
360                                  Sr. Data Engineer
361                    Senior Insurance Data Scientist